apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullPolicy: Always
      containers:
      - name: fastapi
        image: albertriu1998/fastapi
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef: 
                name: app-secret
                key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef: 
                name: app-secret
                key: password
        - name: POSTGRESQL_ADDRESS
          value: "10.99.254.159"