apiVersion: v1
stringData:
  username: {{ .Values.database.owner }}
  password: {{ .Values.database.password }}
kind: Secret
metadata:
  name: app-secret
  annotations:
    helm.sh/hook: pre-install
type: kubernetes.io/basic-auth