apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  labels:
    job: node-api
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: web